# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "infotainment"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM:
    # vb.memory = "1024"
  end

  # Bash Script
  #  config.vm.provision :shell, :path => "script.sh" # runs script file
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-add-repository -y ppa:webupd8team/atom
    sudo apt-get update

    # install programs
    echo "---------------INSTALLING PACKAGES---------------"
    declare -a program=(
      "chromium-browser"
      "curl"
      "git"
      "npm"
      "vim"
      "terminator"
      "atom"
      "python"
      "python-pip"
      "python-numpy" )
    for i in "${program[@]}"
      do
         echo "Installing $i ..."
         apt-get -y install "$i"
      done

    # install pip python packages
    echo "---------------INSTALLING PYTHON PACKAGES---------------"
    declare -a py=(
      "flask"
      "virtualenv"
      "requests"
      "ipython"
      "csv"  )
    for i in "${py[@]}"
      do
         echo "Installing $i ..."
         pip install "$i"
      done

    # install npm node packages
    sudo ln -s /usr/bin/nodejs /usr/bin/node # symlink for node
    echo "---------------INSTALLING NODE PACKAGES---------------"
    declare -a node=(
      "electron-prebuilt"
      "gulp" )
    for i in "${node[@]}"
      do
         echo "Installing $i ..."
         npm install -g "$i"
      done

    # upgrade and clean up
    sudo apt-get upgrade -y
    # sudo apt-get dist-upgrade -y
    sudo apt-get autoremove -y
    sudo apt-get autoclean -y
  SHELL
end
